// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class HomeLinkFunction {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void testHomeLinkFunction() throws Exception{
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.cssSelector(".menu-item:nth-child(2) .font-text")).click();
    driver.findElement(By.name("linkName")).click();
    driver.findElement(By.name("linkName")).click();
    driver.findElement(By.cssSelector(".layui-btn")).click();
    driver.findElement(By.name("linkName")).sendKeys("百度");
    driver.findElement(By.cssSelector(".layui-btn")).click();
    driver.findElement(By.name("linkUrl")).click();
    driver.findElement(By.name("linkUrl")).sendKeys("https://www.baidu.com/");
    driver.findElement(By.cssSelector(".layui-btn")).click();
    driver.findElement(By.name("linkDescription")).sendKeys("百度一下，你就知道");
    driver.findElement(By.cssSelector(".layui-btn")).click();
  }

  public static void main(String args[]){
    String url="http://localhost:8080/";
    System.setProperty("webdriver.gecko.driver", "src\\test\\geckodriver.exe");
    HomeLinkFunction test=new HomeLinkFunction();
    try {
      test.setUp();
      test.testHomeLinkFunction();
      test.tearDown();
    }catch(Exception e){
      e.printStackTrace();
    }
  }
}
