// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class HomeMenuAndSidebarFunction {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testHomeAndSidebarFunction() throws Exception{
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.cssSelector(".menu-item:nth-child(3) .font-text")).click();
    driver.findElement(By.linkText("测试个人博客系统")).click();
    driver.findElement(By.cssSelector(".menu-item:nth-child(4) .font-text")).click();
    driver.findElement(By.linkText("MySQL常用命令语句")).click();
    driver.findElement(By.cssSelector(".tag-link-129:nth-child(1)")).click();
    driver.findElement(By.linkText("Java中File类的使用")).click();
  }

  public static void main(String args[]){
    String url="http://localhost:8080/";
    System.setProperty("webdriver.gecko.driver", "src\\test\\geckodriver.exe");
    HomeMenuAndSidebarFunction test=new HomeMenuAndSidebarFunction();
    try {
      test.setUp();
      test.testHomeAndSidebarFunction();
      test.tearDown();
    }catch(Exception e){
      e.printStackTrace();
    }
  }
}
