// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class HomeArticleFunction {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void testHomeArticleFunction() throws Exception {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("数据库")).click();
    vars.put("win378", waitForWindow(2000));
    driver.switchTo().window(vars.get("win378").toString());
    driver.findElement(By.linkText("MySQL常用命令语句")).click();
    driver.findElement(By.cssSelector("li:nth-child(1) .font-text")).click();
    driver.findElement(By.linkText("阅读全文")).click();
    driver.findElement(By.cssSelector(".tag-link-129:nth-child(1)")).click();
    driver.findElement(By.linkText("Java中ImageIcon路径问题")).click();
    driver.findElement(By.cssSelector(".favorite")).click();
  }

  public static void main(String args[]){
    String url="http://localhost:8080/";
    System.setProperty("webdriver.gecko.driver", "src\\test\\geckodriver.exe");
    HomeArticleFunction test=new HomeArticleFunction();
    try {
      test.setUp();
      test.testHomeArticleFunction();
      test.tearDown();
    }catch(Exception e){
      e.printStackTrace();
    }
  }
}
