// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void () {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.cssSelector(".menu-item:nth-child(2) .font-text")).click();
    driver.findElement(By.name("linkName")).click();
    driver.findElement(By.name("linkName")).click();
    driver.findElement(By.cssSelector(".layui-btn")).click();
    driver.findElement(By.name("linkName")).sendKeys("百度");
    driver.findElement(By.cssSelector(".layui-btn")).click();
    driver.findElement(By.name("linkUrl")).click();
    driver.findElement(By.name("linkUrl")).sendKeys("https://www.baidu.com/");
    driver.findElement(By.cssSelector(".layui-btn")).click();
    driver.findElement(By.name("linkDescription")).sendKeys("百度一下，你就知道");
    driver.findElement(By.cssSelector(".layui-btn")).click();
    assertThat(driver.switchTo().alert().getText(), is("申请成功，请耐心等待审核！"));
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.id("user_login")).click();
    driver.findElement(By.id("user_login")).sendKeys("admin");
    driver.findElement(By.id("user_pass")).click();
    driver.findElement(By.id("user_pass")).sendKeys("123456");
    driver.findElement(By.id("submit-btn")).click();
    driver.findElement(By.linkText("链接")).click();
    driver.findElement(By.linkText("设置")).click();
    driver.findElement(By.linkText("菜单")).click();
    driver.findElement(By.linkText("链接")).click();
    driver.findElement(By.linkText("全部链接")).click();
    driver.findElement(By.linkText("编辑")).click();
    driver.findElement(By.cssSelector(".layui-unselect:nth-child(3) > .layui-anim")).click();
    driver.findElement(By.cssSelector(".layui-input-block > .layui-btn")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("前台")).click();
    vars.put("win2893", waitForWindow(2000));
    driver.switchTo().window(vars.get("win2893").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("百度")).click();
    vars.put("win260", waitForWindow(2000));
    driver.switchTo().window(vars.get("win260").toString());
  }
}
